#define ARM_NUM 2
#define UPPER_ARM_R_RANGE 700.0 //ToDo: 上側アームのアーム長可動域(mm)
#define UPPER_ARM_R_MIN 200.0   //ToDo: アーム長を一番短くしたときのR(mm)を測る
#define UPPER_ARM_DEG_RANGE 180
#define UPPER_ARM_DEG_MIN 0

#define LOWER_ARM_R_RANGE 830.0 //ToDo: 下側アームのアーム長可動域(mm)
#define LOWER_ARM_R_MIN 200.0   //ToDo: アーム長を一番短くしたときのR(mm)を測る
#define LOWER_ARM_DEG_RANGE 180
#define LOWER_ARM_DEG_MIN 0

#define R_ROBOMAS_DIAMETER 30.0 //アーム長ロボマスにつくギアの直径(mm)

#define POLAR_RATIO (8.0/3.0) //アーム軸/モーター軸　直径比

#define LOWER_ARM_HOME_COORDINATE {\
  .x = LOWER_ARM_R_MIN,\
  .y = 0,\
}
#define UPPER_ARM_HOME_COORDINATE {\
  .x = UPPER_ARM_R_MIN,\
  .y = 0,\
}

//HOMING
#define HOMING_UPPER_ARM_TIMEOUT_MS 10000
#define HOMING_LOWER_ARM_TIMEOUT_MS 10000

#define HOMING_TIMEOUT_MARGIN_RATE 0.6

//                                                                  rotation   per  second
#define HOMING_UPPER_DEG_RPM  ((UPPER_ARM_DEG_RANGE / 360 * POLAR_RATIO)        /   (HOMING_UPPER_ARM_TIMEOUT_MS/1000.0/60.0 * HOMING_TIMEOUT_MARGIN_RATE))
#define HOMING_LOWER_DEG_RPM  ((LOWER_ARM_DEG_RANGE / 360 * POLAR_RATIO)        /   (HOMING_LOWER_ARM_TIMEOUT_MS/1000.0/60.0 * HOMING_TIMEOUT_MARGIN_RATE))
#define HOMING_UPPER_R_RPM    ((UPPER_ARM_R_RANGE/(R_ROBOMAS_DIAMETER * M_PI))  /   (HOMING_UPPER_ARM_TIMEOUT_MS/1000.0/60.0 * HOMING_TIMEOUT_MARGIN_RATE))
#define HOMING_LOWER_R_RPM    ((LOWER_ARM_R_RANGE/(R_ROBOMAS_DIAMETER * M_PI))  /   (HOMING_LOWER_ARM_TIMEOUT_MS/1000.0/60.0 * HOMING_TIMEOUT_MARGIN_RATE))
